branches:
  only:
    - master

sudo: required

services:
  - docker

# before_install:
#   - sudo apt-get -qq update
#   - sudo apt-get -qq install -y jq

script:
  - echo "TODO"
#  - docker build --force-rm -t minecraftserver/portals .

after_success:
  # - TODO: Do something neat!
